# recovery stand
#target_jpos: [
#    -0.5, -1.1, 2.4,
#    0.5, -1.1, 2.4,
#    -0.5, -1.1, 2.5,
#    0.5, -1.1, 2.5]

target_jpos: [
  -0.0, -1.4, 2.7,
  0.0, -1.4, 2.7,
  -0.0, -1.4, 2.7,
  0.0, -1.4, 2.7]

#mid_jpos: [
#    -1.8, 0., 2.7,
#    1.8, 0., 2.7,
#    -1.7, 0.5, 0.5,
#    1.7, 0.5, 0.5]
#mid_jpos: [
  #  -3.0, 0., 2.7,
  #  3.0, 0., 2.7,
  #  -3.0, 0.5, 0.5,
  #  3.0, 0.5, 0.5 ]

mid_jpos: [
  -2.3, 0., 2.7,
  2.3, 0., 2.7,
  -2.3, 0.5, 0.5,
  2.3, 0.5, 0.5 ]
