delta_jpos: [
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0 ]

mid_jpos: [
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0 ]
#target_jpos: [
#    0., .0, .7,
#    0., .0, .7,
#    0., .0, .7,
#    0., .0, .7]

#target_jpos: [
#  -0.6, -0.0, 2.7,  # RF 0 abad + hip + knee
#  0.6, -0.5236, 2.7, # LF 1
#  -0.6, -0.7854, 2.7,  # RB 2
#  0.6, -1.0472, 2.7, ]  # LB 3

  #target_jpos: [
  #    0, 0, 0,    # 0
  #    0, 0, 0,     # 3
  #    1.177, 8.083, -2.267,      # 6
  #    0, 0, 0,]      # 9

#mid_jpos: [
#  -0.6, -0.0, 2.7,  # RF 0 abad + hip + knee
#  0.6, -0.5236, 2.7, # LF 1
#  -0.6, -0.7854, 2.7,  # RB 2
#  0.6, -1.0472, 2.7, ]  # LB 3